Add properties
helenver/TRL-Trello pull request #1
Opened 2023-04-16 16:24 UTC by helenver

2023-04-18 14:45 UTC, ruslan-tyshchanka requested changes

2023-04-18 14:45 UTC, ruslan-tyshchanka commented on src/main/resources/properties/environment/Trello/environment.properties
> +variables.Email=ENC(NCnnukNOy5FJQadSBgoWOLCR7EPMH7Qjltvs8+iWsbM=)
All your variable names start with small letter. Please update Email variable name accordingly

2023-04-18 14:45 UTC, ruslan-tyshchanka commented on src/main/resources/properties/configuration.properties
> +configuration.environments=Trello
Please specify type of environent here (prod,dev,test), not application name

2023-04-18 17:39 UTC, helenver commented on src/main/resources/properties/environment/Trello/environment.properties
> +variables.Email=ENC(NCnnukNOy5FJQadSBgoWOLCR7EPMH7Qjltvs8+iWsbM=)
+

2023-04-21 07:02 UTC, ruslan-tyshchanka approved these changes

2023-04-24 04:32 UTC, merged