TRL-006 Rules_verification
helenver/TRL-Trello pull request #10
Opened 2023-05-30 20:28 UTC by helenver

[allure.zip](https://github.com/helenver/TRL-Trello/files/11605144/allure.zip) was updated on 30.05 at 23.20

Scope:
Preconditions:
Create a board via API
Create cards via API

Verifications:
Create an action in the 'Card Move' section
Add the trigger from the 'Move' section
Add the trigger from the 'Add/Remove' section
Add the trigger from the 'Dates' section
Add the trigger from the 'Content' section
Delete the added trigger from the 'Content' section
Save the created rule
Delete the created rule
Delete the board

2023-05-31 06:14 UTC, ruslan-tyshchanka commented
Please make scope more business like. Focus more on identifying the business rules which are verified in this PR, rather then enlisting the steps from test story

2023-05-31 06:16 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/rules_checks.story
> +Scenario: Select a trigger in "Card Move" section
Comment from PR scope also applies to Scenario names. Story is called rules_checks, and yet there are only two scenario rules with 'rules are saved' and 'rules are deleted'

2023-05-31 06:20 UTC, ruslan-tyshchanka requested changes

2023-05-31 06:20 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/rules_checks.story
> +Scenario: Remove the created rule
The rule is saved, and then immediately deleted in the next scenario. Where are rules verification scenarios?

2023-06-01 04:33 UTC, helenver commented on src/main/resources/story/regression/rules_checks.story
> +Scenario: Remove the created rule
I have added

2023-06-01 16:40 UTC, ruslan-tyshchanka commented
Please add rules verification after rule was created and updated, and also check that rule wasn't applied after its deletion

2023-06-02 04:52 UTC, ruslan-tyshchanka approved these changes

2023-06-02 06:18 UTC, merged