TRL-002 Main_page_checks
helenver/TRL-Trello pull request #3
Opened 2023-04-26 05:48 UTC by helenver

2023-04-28 15:50 UTC, ruslan-tyshchanka commented
Please define a scope of verifications which were implemented in this PR in Description section

2023-04-28 15:50 UTC, ruslan-tyshchanka requested changes

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/properties/configuration.properties
> +web.screenshot.strategy.custon.native-header-to-cut=80
Are you sure that you need all those properties? If so, plesse describe why do you need them

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/properties/environment/prod/environment.properties
> +variables.action-type=COMPARE_AGAINST
Please remove this property from environment properties

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/properties/suite/smoke/suite.properties
> +variables.action-type=COMPARE_AGAINST
Please remove this propert from suite properties

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/steps/composite.steps
> +Composite: When I log as a registered user
You can rename it to 'When I log in'. The fact that user is registered is implied - you cannot login with unregestered user

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/steps/composite.steps
> +Composite: When I log in with non-existent credentials
How often will you use this composite? Seems like a single negative case. Why did you include that in composite file?

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/steps/composite.steps
> +When I click on element located by `By.xpath(//header[@data-testid='bignav']//a[@href='/login'])`
Please shorten xpaht if that's applicable

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/steps/composite.steps
> +When I scroll element located `By.xpath(//input[@id='user'])` into view
Pleae investigate if there is a way of using ID as locator, not whole xpath (here and further)

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Scenario:Verify that user can log in
Please add space between Scenario: and its name

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +|By.xpath(//button[@title='Workspaces'])|Your Workspace                                          |
please include only title values in examplea table, not the whole xpath

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +  @severity 1
Why do you use severity meta tag only for one scenario? Hopw are you planning to use it in future?

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +|webHeaderToCut|webFooterToCut |scrollTimeout|shootingStrategy|cutRight|
Please explain this step and the configurations which are used here.

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Then text `team board` exists
Is team board a default board on website or did you create it earlier?

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Scenario: Verify that user can open his notifications
their* notification

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +When I wait until element located by `By.xpath(//section[@data-testid])` appears
hy can't you just wait for text to appear?

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Examples:
Why is examples table used here? There is only one iteration in the scope of scenario (here and further)

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Scenario: Verify that user can open his "account" tab
their

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Scenario:Verify that user can log in
Please change story name, do not use [] brackets
Also, you'll have to use Logged_user prefix in every story if you start this pattern now so please think about a better way to name it

2023-04-28 15:50 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/[Non-logged user]main_page.story
> +Scenario: Verify the elements in the header for non-logged user
Not-logged user can be changed to 'unauthorized' or something like that.

2023-04-28 18:12 UTC, helenver commented on src/main/resources/story/smoke/[Non-logged user]main_page.story
> +Scenario: Verify the elements in the header for non-logged user
Done

2023-04-28 18:16 UTC, helenver commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Scenario:Verify that user can log in
done

2023-04-28 18:17 UTC, helenver commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Scenario: Verify that user can open his "account" tab
Done

2023-04-28 18:19 UTC, helenver commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Examples:
Corrected

2023-04-28 18:21 UTC, helenver commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Scenario: Verify that user can open his notifications
corrected

2023-04-28 18:23 UTC, helenver commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Then text `team board` exists
I have created board 'team board' in advanced in regression story

2023-04-28 18:36 UTC, helenver commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +  @severity 1
I used this tag to prioritize this scenario to be run the first. If I had the lack of time I could run scenarioes with severity 1 / 2 and skip with severity 5

2023-04-28 18:38 UTC, helenver commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +Scenario:Verify that user can log in
Done

2023-04-28 18:39 UTC, helenver commented on src/main/resources/steps/composite.steps
> +Composite: When I log in with non-existent credentials
I have included it in the story

2023-04-28 18:40 UTC, helenver commented on src/main/resources/steps/composite.steps
> +Composite: When I log as a registered user
Done

2023-04-28 18:41 UTC, helenver commented on src/main/resources/properties/suite/smoke/suite.properties
> +variables.action-type=COMPARE_AGAINST
Done

2023-04-28 18:42 UTC, helenver commented on src/main/resources/properties/environment/prod/environment.properties
> +variables.action-type=COMPARE_AGAINST
Done

2023-04-29 05:17 UTC, helenver commented on src/main/resources/properties/environment/prod/environment.properties
> +variables.action-type=COMPARE_AGAINST
Done

2023-04-29 05:19 UTC, helenver commented on src/main/resources/properties/suite/smoke/suite.properties
> +variables.action-type=COMPARE_AGAINST
Done

2023-04-29 05:23 UTC, helenver commented on src/main/resources/properties/configuration.properties
> +web.screenshot.strategy.custon.native-header-to-cut=80
I have checked that I can use only configuration in the step to cut the page. I removed these properties

2023-04-29 05:23 UTC, helenver commented on src/main/resources/steps/composite.steps
> +Composite: When I log as a registered user
Done

2023-04-29 05:23 UTC, helenver commented on src/main/resources/story/smoke/[Non-logged user]main_page.story
> +Scenario: Verify the elements in the header for non-logged user
I used it to prioritize this Scenario to be run the first

2023-04-29 06:00 UTC, helenver commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +|webHeaderToCut|webFooterToCut |scrollTimeout|shootingStrategy|cutRight|
I cut the page to check only elements in the left menu. I needed to cut some parts of the page because they can be different and my test fails. I removed all of them besideы 'cutRight'

2023-04-29 11:23 UTC, helenver commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +When I wait until element located by `By.xpath(//section[@data-testid])` appears
It is the next step. I will remove this one

2023-04-29 11:56 UTC, helenver commented on src/main/resources/steps/composite.steps
> +When I scroll element located `By.xpath(//input[@id='user'])` into view
I changed By.xpath to By.id

2023-04-29 16:23 UTC, helenver commented on src/main/resources/steps/composite.steps
> +When I click on element located by `By.xpath(//header[@data-testid='bignav']//a[@href='/login'])`
There are 3 elements with 'href=/login' on the page. I have to write such long to define the node

2023-04-29 16:31 UTC, helenver commented on src/main/resources/story/smoke/[Logged user]main_page.story
> +|By.xpath(//button[@title='Workspaces'])|Your Workspace                                          |
I didn't get this comment (

2023-05-02 07:10 UTC, ruslan-tyshchanka requested changes

2023-05-02 08:49 UTC, helenver commented on src/main/resources/story/regression/regression.story
> +Scenario: Verify that user can create board with workspace visibility
I have changed to board_verification.It will include checks which refer to a board. The last scenario was deleted

2023-05-02 08:50 UTC, helenver commented on src/main/resources/story/smoke/main_page_for_authorized_user.story
> +||HeaderElement  |text                                                    |
Done

2023-05-02 11:06 UTC, ruslan-tyshchanka requested changes

2023-05-02 11:06 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/board_verification.story
> +Scenario: Verify that user can create board with workspace visibility
Is it okay that 'new board' board will be created during every test execution?

2023-05-02 11:06 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/main_page_for_authorized_user.story
> +When I Establish baseline with name `information` ignoring:
establish action is used here

2023-05-02 11:06 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/main_page_for_authorized_user.story
> +When I Compare_against baseline with name `theme`
Please use the same baselineAction pattern in your repository - with capital letters

2023-05-02 11:06 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/regression.story
> +Scenario: Verify that user can create board with workspace visibility
Trello is basically an application for board managing, so it looks like the whole application critical path is going to be executed in one story. Please be more specific.

2023-05-02 11:12 UTC, helenver commented on src/main/resources/story/smoke/main_page_for_authorized_user.story
> +|HeaderElement  |text                                                    |
Done

2023-05-02 11:16 UTC, helenver commented on src/main/resources/story/regression/board_verification.story
> +Scenario: Verify that user can create board with workspace visibility
This story is in the regression file. In addition It will be deleted after every creation. I suppose that it s a critical path test. Trello sets the limit for board creation

2023-05-02 11:17 UTC, helenver commented on src/main/resources/story/smoke/main_page_for_authorized_user.story
> +When I Establish baseline with name `information` ignoring:
Corrected

2023-05-02 11:18 UTC, helenver commented on src/main/resources/story/smoke/main_page_for_authorized_user.story
> +When I Compare_against baseline with name `theme`
corrected

2023-05-02 11:30 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/main_page_for_unauthorized_user.story
> +Given I initialize story variable `visualCheck` with value `COMPARE_AGAINST`
there is only one visual check in scope of story, there is no need for this cariable establishment

2023-05-02 11:34 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/board_verification.story
> +Scenario: Verify that user can create board with workspace visibility
I'd rather either deleted this check or implemented the deletion of the board right after it was created.
Or at least added some unique pattern to a board name (.e.g New Board <uniqueGeneratedCode>

2023-05-02 11:47 UTC, helenver commented on src/main/resources/story/regression/board_verification.story
> +Scenario: Verify that user can create board with workspace visibility
I have cleared this story.

2023-05-02 11:48 UTC, helenver commented on src/main/resources/story/smoke/main_page_for_unauthorized_user.story
> +Given I initialize story variable `visualCheck` with value `COMPARE_AGAINST`
Deleted this step

2023-05-02 12:03 UTC, ruslan-tyshchanka approved these changes

2023-05-02 15:37 UTC, merged