TRL-003 Board_creation
helenver/TRL-Trello pull request #5
Opened 2023-05-02 18:37 UTC by helenver

[allure.zip](https://github.com/helenver/TRL-Trello/files/11406849/allure.zip)  was updated 05.05 at 16.50 p.m

**Scope of verifications:**

- New board creation
- Add some cards to the created board
- Some visual checks of DDL elements on the page of the created board
- New board deletion
- Log in (positive/negative)
- Log out

2023-05-03 07:01 UTC, ruslan-tyshchanka requested changes

2023-05-03 07:01 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/new_board_creation.story
> +When I click on element located by `By.xpath(//a[contains(@class,'js-open-more')])`
Do we need a 'js' part of class?

2023-05-03 07:01 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/new_board_creation.story
> +When I wait until element located by `By.xpath(//span[text()='Board deleted.'])` appears
Please verify that the board really was deleted, not just the message

2023-05-03 07:01 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/new_board_creation.story
> +
Empty line

2023-05-03 07:01 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/new_board_creation.story
> +Scenario: Verify that user can create a board with workspace visibility
You can skip 'verify' part in scneario name

2023-05-03 17:34 UTC, helenver commented on src/main/resources/properties/configuration.properties
> +configuration.suites=regression
To run regression story. Should I use overriden properties?

2023-05-03 17:37 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +Scenario: Verify that user can create a board with workspace visibility
Corrected

2023-05-03 17:38 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +When I click on element located by `By.xpath(//a[contains(@class,'js-open-more')])`
Deleted it

2023-05-03 17:44 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +Scenario: Verify that user can create a board with workspace visibility
There are three options in the creation pop-up. In this scenario I create board with workspace visibility
![Monosnap Trello Workspace ](https://user-images.githubusercontent.com/87672817/236000865-ed3e6ff9-7434-4f80-b60b-439f844bb358.png)

2023-05-03 17:45 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +Scenario: Verify that user can add some cards to the created board
Deleted

2023-05-03 18:05 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +When I wait until element located by `By.xpath(//span[text()='Board deleted.'])` appears
I have added this step : **When I wait until element located by `By.xpath...` disappears**

2023-05-03 18:07 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +When I log in
Done

2023-05-04 05:18 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +When I click on element located by `By.xpath(//*[@aria-label='Create board or Workspace'])`
Done ✅

2023-05-04 16:20 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +Scenario: Verify that user can create a board with workspace visibility
I have added the separete login story in regression

2023-05-04 17:50 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +When I enter `new board` in field located by `By.xpath(//*/input[@type='text'])`
Done ✅

2023-05-04 18:01 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +|//input[@class='list-name-input']|//input[@value='Add list']|//span[text()='Add a card']                                        |
Oh, I see I doubled the same click on the same field. I have deleted it

2023-05-04 18:08 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +When I COMPARE_AGAINST baseline with name `Customize_view`
I didn't get. I need your help

2023-05-05 06:56 UTC, ruslan-tyshchanka requested changes

2023-05-05 06:56 UTC, ruslan-tyshchanka commented on src/main/resources/properties/configuration.properties
> +configuration.suites=regression
Yes. Configuration properties are the default properties to which automation should generally refer during test execution. If we want to run specific suites or specific scenarios, we should override this property in overriding.properties file, not directly from here

2023-05-05 06:56 UTC, ruslan-tyshchanka commented on src/main/resources/properties/configuration.properties
> +ui.visual.baseline-storage.filesystem.folder=/Users/Alena_Veratsennikava/Trello/src/main/resources/baselines
What will happen if this repository will requre execution on different device (e.g. my laptop) - there will be no /Users/Alena_Veratsennikava/ path there

2023-05-05 06:56 UTC, ruslan-tyshchanka commented on src/main/resources/steps/composite.steps
> +Composite: When I log in with $email, $password
Please change comma to 'and' or something like it.

2023-05-05 06:56 UTC, ruslan-tyshchanka commented on src/main/resources/steps/composite.steps
> +Composite: When user logs in with $email, $password
When user logs in and When I log in - why do you use different scenarios?

2023-05-05 06:56 UTC, ruslan-tyshchanka commented on src/main/resources/steps/composite.steps
> +When I click on element located by `By.id(login)`
Please take a look at the newline requirement sign in the end of the story (here and further)

2023-05-05 06:56 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/login_checks.story
> +Scenario: User can not log in with invalid password
Three similar scenarios, try using examples table with different data set

2023-05-05 06:56 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/new_board_creation.story
> +|//input[@class='list-name-input']|//input[@value='Add list']|//span[text()='Add a card']                                        |
Still, please describe what do these cases mean - what do they verify and how do they differ

2023-05-05 06:56 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/new_board_creation.story
> +When I COMPARE_AGAINST baseline with name `Customize_view`
Please add baselines from previous PR as well and attach allure report for all the tests in repository

2023-05-05 06:56 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/new_board_creation.story
> +Scenario: Elements in the Automation DDL
What elements? Click on them, check them, multi-select them?

2023-05-05 06:56 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/new_board_creation.story
> +When I wait until element located by `By.xpath(//a[contains(@href,'${NewBoardName}')])` disappears
You never previously established the existence of this element (or maybe i didn't find it) - so how can we be sure that the absence of element by this locator means that the board was deleted?

2023-05-05 08:17 UTC, helenver commented on src/main/resources/steps/composite.steps
> +Composite: When I log in with $email, $password
Done ✅

2023-05-05 08:32 UTC, helenver commented on src/main/resources/steps/composite.steps
> +Composite: When user logs in with $email, $password
In different case the last step is different (log in button is diiferent)
I have corrected

2023-05-05 08:42 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +Scenario: Elements in the Automation DDL
I check that this DDL contains options . Visual check of elements display in the Automation DDL

2023-05-05 08:56 UTC, helenver commented on src/main/resources/steps/composite.steps
> +When I click on element located by `By.id(login)`
I have deleted newline requirement sign

2023-05-05 09:10 UTC, helenver commented on src/main/resources/story/regression/login_checks.story
> +Scenario: User can not log in with invalid password
I have used the Examples table for two of them because in the third the last button is different

2023-05-05 10:25 UTC, helenver commented on src/main/resources/properties/configuration.properties
> +configuration.suites=regression
I have added overriding properties and filled them

2023-05-05 11:47 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +When I wait until element located by `By.xpath(//a[contains(@href,'${NewBoardName}')])` disappears
There was not but I have added

2023-05-05 13:21 UTC, ruslan-tyshchanka commented on src/main/resources/overriding.properties
> +batch-1.resource-location=story/smoke
Please put overriding properties in git ignore file - modifications with this file should be displayed only locally in your IDE

2023-05-05 13:32 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/new_board_creation.story
> +Scenario: Elements in the Automation DDL
Please reflect it in the scneario name

2023-05-05 13:33 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/new_board_creation.story
> +Then field located `By.xpath(//h3[contains(text(),"YOUR WORKSPACES")]//..//a[contains(@href,'${NewBoardName}')])` exists
Locator seems too big. Can it be shortened?

2023-05-05 13:52 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +Then field located `By.xpath(//h3[contains(text(),"YOUR WORKSPACES")]//..//a[contains(@href,'${NewBoardName}')])` exists
I have specified the first part because there are 2 the same elements on the page

2023-05-05 13:54 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +Scenario: Elements in the Automation DDL
I have renamed to " Visual display of elements in the Customize views DDL "

2023-05-05 14:00 UTC, helenver commented on src/main/resources/story/regression/login_checks.story
> +Scenario: User can not log in with invalid password
I have returned to 3 separate scenarioes

2023-05-05 14:03 UTC, helenver commented on src/main/resources/overriding.properties
> +batch-1.resource-location=story/smoke
I have added but not sure if it is correct

2023-05-05 14:22 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +|//input[@class='list-name-input']|//input[@value='Add list']|//span[text()='Add a card']                                        |
At first I need to add list , the card is added to the list  after it I move to a new list and do the same. Shoul I change the logic of this check ?

2023-05-05 15:25 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/new_board_creation.story
> +|//input[@class='list-name-input']|//input[@value='Add list']|//span[text()='Add a card']                                        |
No need to change logic, just make it more clear - maybe update scenario name or add comments

2023-05-05 15:28 UTC, ruslan-tyshchanka commented on src/main/resources/overriding.properties
> +batch-1.resource-location=story/smoke
Seems like it isn't correct, file is still visible here. Please investigate or move this scope to the next PR

2023-05-05 15:40 UTC, helenver commented on src/main/resources/story/regression/new_board_creation.story
> +Then field located `By.xpath(//h3[contains(text(),"YOUR WORKSPACES")]//..//a[contains(@href,'${NewBoardName}')])` exists
It works. I have changed mine

2023-05-05 15:43 UTC, helenver commented on src/main/resources/story/smoke/main_page_for_unauthorized_user.story
> +When I ESTABLISH baseline with name `MainPage` ignoring:
Corrected

2023-05-05 16:10 UTC, ruslan-tyshchanka approved these changes

2023-05-05 16:18 UTC, ruslan-tyshchanka requested changes
please update baselines, newlines and overriding properties issues

2023-05-10 08:21 UTC, ruslan-tyshchanka requested changes

2023-05-10 08:21 UTC, ruslan-tyshchanka commented on src/main/resources/properties/suite/regression/suite.properties
> +batch-1.resource-include-patterns=new_board_creation.story
this change should be done to your local overriding properties file, not here

2023-05-10 08:21 UTC, ruslan-tyshchanka commented on src/main/resources/story/smoke/main_page_for_authorized_user.story
> +!-- When I click on element located by `By.xpath(//*[@data-testId='HelpIcon'])`
Please remove commented steps

2023-05-10 09:32 UTC, ruslan-tyshchanka approved these changes

2023-05-12 16:22 UTC, merged