TRL-005 Filter_verification
helenver/TRL-Trello pull request #9
Opened 2023-05-24 20:23 UTC by helenver

[allure.zip](https://github.com/helenver/TRL-Trello/files/11558800/allure.zip) was added on 24.05 at 23.20

Scope:
Check filter options:
search field
search cards by options

2023-05-25 16:22 UTC, ruslan-tyshchanka requested changes

2023-05-25 16:22 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +Given request body: {"name"= "${cardName}", "idList"= "${listId}", "due"= "2023-05-30T19:27:00.000Z"}
Please generate date instead of hardcode

2023-05-25 16:22 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +|name        |value           |
Please align table

2023-05-25 16:22 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +When I click on element located by `By.xpath(//a[@aria-label="Close dialog"])`
All the scenarios before this one look like a precondition. Do we need all of then in here?

2023-05-25 16:22 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +Scenario: Add card to the list via UI
Please do it via API

2023-05-25 16:22 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +Scenario: Assign the card to yourself
Please do it via API. It's a precondition and there is no need to spend test execution time omn ui steps

2023-05-25 16:42 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +When I wait until element located by `By.xpath(//span[@data-testid="filter-popover-button-card-count"])` appears
Xpath is too vague, please specifiy number of elelments displayed in pop over

2023-05-25 16:43 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +When I wait until element located by `By.xpath(//span[text()='${cardName}'])` appears
Verify that another card is not diaplayed on page

2023-05-25 16:47 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +Scenario: Find the card by 'Due in the next week week' option
Done ✅

2023-05-25 18:07 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +Given request body: {"name"= "${cardName}", "idList"= "${listId}", "due"= "2023-05-30T19:27:00.000Z"}
Done ✅

2023-05-25 18:07 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +|name        |value           |
Done ✅

2023-05-25 18:21 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +When I click on element located by `By.xpath(//a[@aria-label="Close dialog"])`
I have created the precondition story for first scenarioes

2023-05-25 18:22 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +Given I initialize story variable `SecondcardName` with value `#{generate(Book.title)}`
SecondcardName -> secondCardName

2023-05-25 18:50 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +When I click on element located by `By.xpath((//p[text()='Members']//following::label/span)[3])`
//*[@title="No members"]//following::label/span[1] ; //*[@title="Cards assigned to me"]//preceding::label/span[1]

2023-05-25 18:52 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +When I click on element located by `By.xpath((//p[text()='Members']//following::label/span)[3])`
I do not like them 😕 either

2023-05-25 19:31 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +When I wait until element located by `By.xpath(//span[text()='${cardName}'])` appears
Then the text '${secondCardName}'/${cardName}' does not exist - I have added

2023-05-25 19:52 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +GivenStories:/story/precondition/create_api_board.story
I have added check where some/no cards are displayed according to the set option(s) in filter

2023-05-26 04:51 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +Scenario: Assign the card to yourself
Done ✅

2023-05-26 04:52 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +Scenario: Add card to the list via UI
Done ✅

2023-05-26 04:52 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +Given I initialize story variable `SecondcardName` with value `#{generate(Book.title)}`
Done ✅

2023-05-26 08:59 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +When I click on element located by `By.xpath((//p[text()='Members']//following::label/span)[3])`
Done ✅

2023-05-26 12:49 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +When I click on element located by `By.xpath((//p[text()='Members']//following::label/span)[3])`
Corrected

2023-05-26 13:03 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +When I click on element located by `By.xpath(//div[@title='${boardName}'])`
What is this step for?

2023-05-26 13:03 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +When I log in with ${email} and ${password}
Please move login to a separate scenario

2023-05-26 13:07 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +Then the text '${cardName}' does not exist
It'll be better to use 'Then number of elements on page is equal to <>' step here

2023-05-26 13:11 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +When I wait until element located by `By.xpath(//span[text()='${cardName}'])` appears
Why do you use waiter instead of just verifyingthe number of elemnts on page. In case something's wrong with website. it'll take a lot of time for story to finish its execution with so many waiters. Please re,ain them only where it's necessary

2023-05-26 13:12 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +When I log in with ${email} and ${password}
Done ✅

2023-05-26 13:16 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +Then field located `By.xpath(//span[text()='${cardName}'])` exists
This and previous steps seem identical

2023-05-26 13:16 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +When I execute sequence of actions:
Why is this done? You've already cleared the field

2023-05-26 13:20 UTC, ruslan-tyshchanka commented on src/main/resources/story/regression/filter_checks.story
> +Scenario: Find the label in the Filter popover
Please explain what happens in this scenario

2023-05-26 13:28 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +Scenario: Find the label in the Filter popover
I have created the label with the name in preconditions and search this label in the pop-over

2023-05-26 13:29 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +Scenario: Find the label in the Filter popover
![Screenshot 2023-05-26 at 16 28 26](https://github.com/helenver/TRL-Trello/assets/87672817/48b4cba6-914d-4b58-b6d7-e8b578d69d86)

2023-05-26 13:33 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +When I click on element located by `By.xpath(//div[@title='${boardName}'])`
I need to open my board with created cards

2023-05-26 13:53 UTC, helenver commented on src/main/resources/story/regression/filter_checks.story
> +Then field located `By.xpath(//span[text()='${cardName}'])` exists
Removed one of them

2023-05-26 14:07 UTC, ruslan-tyshchanka approved these changes

2023-05-27 18:00 UTC, merged